#ifndef _PYIRSSI_H_
#define _PYIRSSI_H_

#define MODULE_NAME "python"
#include "config.h"
#include "core.h"
#include "common.h"
#include "modules.h"
#include "commands.h"
#include "settings.h"
#include "printtext.h"
#include "statusbar.h"
#include "mainwindows.h"
#include "window-items.h"
#include "window-activity.h"
#include "levels.h"
#include "servers.h"
#include "chat-protocols.h"
#include "channels.h"
#include "queries.h"
#include "nicklist.h"
#include "chatnets.h"
#include "servers-reconnect.h"
#include "masks.h"
#include "misc.h"
#include "rawlog.h"
#include "log.h"
#include "ignore.h"
#include "fe-exec.h"
#include "pidwait.h"

#endif
